# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'acp_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for acp_test
  pod 'Firebase/Database'

end
